services:
  - type: web
    name: piazza-web
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: piazza-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - fromGroup: domains

databases:
  - name: piazza-db
    plan: free

envVarGroups:
  - name: domains
    envVars:
      - key: DOMAIN_NAME
        value: piazza-web-vpl6.onrender.com
      - key: OUTBOUND_EMAIL_DOMAIN
        value: reportify.app